config/routes.rb
Rails.application.routes.draw do

  resources :calendars
  devise_scope :user do
    get '/users/sign_out' => "devise/sessions#destroy"
  end

  get 'calendar/index'
  get 'map/index'

  resources :films
  resources :attaches
  devise_for :users, :controllers => { :sessions => "users/sessions", registrations: "registrations" }
  devise_for :admins, ActiveAdmin::Devise.config
  resources :articles

  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
  root to: "home#index"
end

app/models/admin.rb
class Admin < Patron

  def decrement_invitation_limit!
    #stub functionality because devise invitation call this method to decrement the counter.
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/attach.rb
class Attach < ApplicationRecord
  mount_uploader :source, ImageUploader
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/film.rb
class Film < ApplicationRecord
end

app/models/patron.rb
class Patron < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :confirmable,
  #        :recoverable, :rememberable, :trackable, :validatable
  # self.abstract_class = true
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < Patron
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
  before_action :authenticate_user!
  def show
    render json: @article
  end
  def show
    @article = Article.find(params[:id])
  end
  private
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/attaches_controller.rb
class AttachesController < InheritedResources::Base
  before_action :authenticate_user!
  def show
    render json: @attach
  end
  def show
    @attach = Attach.find(params[:id])
  end
  private
    def attach_params
      params.require(:attach).permit(:title, :source)
    end

end

app/controllers/films_controller.rb
class FilmsController < InheritedResources::Base
  before_action :authenticate_user!
  def show
    render json: @attach
  end
  private
    def film_params
      params.require(:film).permit(:title, :source)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
        success: "alert-success",
        error: "alert-error",
        alert: "alert-danger",
        notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def bootstrap_glyphs_icon(flash_type)
    {
        success: "glyphicon-ok",
        error: "glyphicon-exclamation-sign",
        alert: "glyphicon-warning-sign",
        notice: "glyphicon-info-sign"
    }[flash_type.to_sym] || 'glyphicon-screenshot'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>artykuły</h1>

<table class="table  table-striped">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Nazwa</th>
    <th scope="col">Tekst</th>
    <th scope="col">Pokaż Więcej</th>
  </tr>
  </thead>
  <tbody>
    <% @articles.each_with_index do |article, index| %>
      <tr scope="row">
        <th scope="row"><%= index %></th>
        <td><%= article.title %></td>
        <td><div class="container"><%= render inline: article.description %></div></td>
        <td><%= link_to 'Pokaż', article %></td>
     </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tytuł</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Treść</strong>
  <%= render inline: @article.description %>
</p>

<%= link_to 'Cofnij', articles_path %>

app/views/attaches/_form.html.erb
<%= form_for(attach) do |f| %>
  <% if attach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attach.errors.count, "error") %> prohibited this attach from being saved:</h2>

      <ul>
      <% attach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>załączniki</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Nazwa</th>

    <th scope="col">Pobierz</th>
  </tr>
  </thead>
  <tbody>
  <% @attaches.each_with_index do |attach, index| %>
    <tr>
      <th scope="row"><%= index %></th>
      <td><%= attach.title %></td>

      <td><%= link_to "pobierz", attach.source.to_s, :download => attach.title.to_s %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/attaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @attach.title %>
</p>

<p>
  <strong>Source:</strong>
  <%= @attach.source %>
</p>

<%= link_to 'Edit', edit_attach_path(@attach) %> |
<%= link_to 'Back', attaches_path %>

app/views/films/_form.html.erb
<%= form_for(film) do |f| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Filmy</h1>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nazwa</th>
      <th scope="col">Źródło</th>
    </tr>
  </thead>

  <tbody>
    <% @films.each_with_index do |film, index| %>
    <tr>
        <th scope="row"><%= index + 1 %></th>
        <td ><%= film.title %></td>
        <td class="text-xs-center"><%= render inline:  film.source %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>

<p>
  <strong>Source:</strong>
  <%= @film.source %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>