config/routes.rb
Rails.application.routes.draw do

  resources :calendars
  devise_scope :user do
    get '/users/sign_out' => "devise/sessions#destroy"
  end

  get 'calendar/index'
  get 'map/index'

  resources :films
  resources :attaches
  devise_for :users, :controllers => { :sessions => "users/sessions", registrations: "registrations" }
  devise_for :admins, ActiveAdmin::Devise.config
  resources :articles

  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
  root to: "home#index"
end

app/models/admin.rb
class Admin < Patron

  def decrement_invitation_limit!
    #stub functionality because devise invitation call this method to decrement the counter.
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/attach.rb
class Attach < ApplicationRecord
  mount_uploader :source, ImageUploader
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/film.rb
class Film < ApplicationRecord
end

app/models/patron.rb
class Patron < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :confirmable,
  #        :recoverable, :rememberable, :trackable, :validatable
  # self.abstract_class = true
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < Patron
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
  before_action :authenticate_user!
  def show
    render json: @article
  end
  def show
    @article = Article.find(params[:id])
  end
  private
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/attaches_controller.rb
class AttachesController < InheritedResources::Base
  before_action :authenticate_user!
  def show
    render json: @attach
  end
  def show
    @attach = Attach.find(params[:id])
  end
  private
    def attach_params
      params.require(:attach).permit(:title, :source)
    end

end

app/controllers/calendars_controller.rb
class CalendarsController < InheritedResources::Base

  private

    def calendar_params
      params.require(:calendar).permit(:leader, :source)
    end
end

app/controllers/films_controller.rb
class FilmsController < InheritedResources::Base
  before_action :authenticate_user!
  def show
    render json: @attach
  end
  private
    def film_params
      params.require(:film).permit(:title, :source)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
        success: "alert-success",
        error: "alert-error",
        alert: "alert-danger",
        notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def bootstrap_glyphs_icon(flash_type)
    {
        success: "glyphicon-ok",
        error: "glyphicon-exclamation-sign",
        alert: "glyphicon-warning-sign",
        notice: "glyphicon-info-sign"
    }[flash_type.to_sym] || 'glyphicon-screenshot'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(calendar) do |f| %>
  <% if calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :leader %>
    <%= f.text_field :leader %>
  </div>

  <div class="field">
    <%= f.label :source %>
    <%= f.text_area :source %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<h1><%= current_user.leader %></h1>
<% @calendars.each do |calendar| %>
  <% if calendar.leader == current_user.leader %>
    <%= render inline: calendar.source %>
  <% end %>
<% end %>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Leader:</strong>
  <%= @calendar.leader %>
</p>

<p>
  <strong>Source:</strong>
  <%= @calendar.source %>
</p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>