config/routes.rb
Rails.application.routes.draw do

  resources :calendars
  devise_scope :user do
    get '/users/sign_out' => "devise/sessions#destroy"
  end

  get 'calendar/index'
  get 'map/index'

  resources :films
  resources :attaches
  devise_for :users, :controllers => { :sessions => "users/sessions", registrations: "registrations" }
  devise_for :admins, ActiveAdmin::Devise.config
  resources :articles

  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
  root to: "home#index"
end

app/models/admin.rb
class Admin < Patron

  def decrement_invitation_limit!
    #stub functionality because devise invitation call this method to decrement the counter.
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/attach.rb
class Attach < ApplicationRecord
  mount_uploader :source, ImageUploader
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/film.rb
class Film < ApplicationRecord
end

app/models/patron.rb
class Patron < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :confirmable,
  #        :recoverable, :rememberable, :trackable, :validatable
  # self.abstract_class = true
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < Patron
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/films_controller.rb
class FilmsController < InheritedResources::Base
  before_action :authenticate_user!
  def show
    render json: @attach
  end
  private
    def film_params
      params.require(:film).permit(:title, :source)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
        success: "alert-success",
        error: "alert-error",
        alert: "alert-danger",
        notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def bootstrap_glyphs_icon(flash_type)
    {
        success: "glyphicon-ok",
        error: "glyphicon-exclamation-sign",
        alert: "glyphicon-warning-sign",
        notice: "glyphicon-info-sign"
    }[flash_type.to_sym] || 'glyphicon-screenshot'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Koncepcja</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<body>
<nav class="hamburger-icon" style="text-align: right">
  <button id="btn1" class="hamburger hamburger--collapse" type="button">
    <span class="hamburger-box">
      <span class="hamburger-inner"></span>
    </span>
  </button>
</nav>
<nav class="mobile-nav">
  <%= link_to "mapa myśli", map_index_path, class: "link nav-item nav-link" %>
  <%= link_to "załączniki", attaches_path, class: "link nav-item nav-link" %>
  <%= link_to "kalendarz", calendars_path, class: "link nav-item nav-link" %>
  <%= link_to "filmy", films_path, class: "link nav-item nav-link" %>
  <%= link_to "artykuły", articles_path, class: "link nav-item nav-link" %>
  <%= link_to "panel admin", admin_root_url, class: "link nav-item nav-link" %>
  <% if user_signed_in? %>
    <%= link_to "Wyloguj się", destroy_user_session_path, class: "link nav-item nav-link", :method => 'delete' %>
    <%= link_to "Edytuj Profil", root_url, class: "link nav-item nav-link" %>
  <% else %>
    <%= link_to "Zaloguj się", new_user_session_path, class: "link nav-item nav-link" %>
  <% end %>
</nav>
<nav class="nav">
  <li><%= link_to image_tag("/images/logo.png"), admin_root_url, class: "logo" %></li>
  <%= link_to "mapa myśli", map_index_path, class: "link nav-item nav-link" %>
  <%= link_to "załączniki", attaches_path, class: "link nav-item nav-link" %>
  <%= link_to "kalendarz", calendars_path, class: "link nav-item nav-link" %>
  <%= link_to "filmy", films_path, class: "link nav-item nav-link" %>
  <%= link_to "artykuły", articles_path, class: "link nav-item nav-link" %>
  <%= link_to "LR sklep", "https://sso.lrworld.com/cas/login?service=https%3A%2F%2Fwww.lrworld.com%2Flogin&d=h&locale=pl_pl", target: "_blank", class: "link nav-item nav-link" %>
  <%= link_to "Blog", "https://www.facebook.com/groups/1759332444171219", target: "_blank", class: "link nav-item nav-link" %>
  <% if user_signed_in? %>
    <%= link_to "Wyloguj się", destroy_user_session_path, class: "link nav-item nav-link", :method => 'delete' %>
    <%= link_to "Edytuj Profil", root_url, class: "link nav-item nav-link" %>
  <% else %>
    <%= link_to "Zaloguj się", new_user_session_path, class: "link nav-item nav-link" %>
  <% end %>
</nav>
<div class="container" id="main-container">
  <%= render partial: 'shared/flash' unless flash.empty? %>
  <%= yield %>
</div>
<script>
    const btn = document.querySelector('#btn1');
    const mobile = document.querySelector('.mobile-nav');
    btn.addEventListener('click', () => {
        btn.classList.toggle('is-active');
        mobile.classList.toggle('active');
    })
</script>
</body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in" role='alert'>
      <button class="close" data-dismiss="alert">×</button>
      <span class="glyphicon <%= bootstrap_glyphs_icon(type)%>" aria-hidden="true"></span>
      <span class="sr-only"><%= type.capitalize%>:</span>
      <%= message %>
    </div>
<% end %>